dependencies:
  - name: wNumb
    version: 1.2.0
    src: htmlwidgets/lib/wNumb-1.2.0
    script: wNumb.min.js

  - name: noUiSlider
    version: 14.7.0
    src: htmlwidgets/lib/noUiSlider-14.7.0
    script: nouislider.js
    stylesheet: nouislider.min.css

  - name: el-checkbox
    version: 1.0.0
    src: htmlwidgets/lib/el-checkbox-1.0.0
    stylesheet: checkbox.min.css

  - name: solutionSettings
    version: 1.0-0
    src: htmlwidgets/lib/solutionSettings-1.0.0
    script:
      - ParameterSetting-class.js
      - IncludeSetting-class.js
      - MultiThemeSetting-class.js
      - SingleThemeSetting-class.js
      - WeightSetting-class.js
      - label-text.js
      - utils.js
      - SolutionSettings-class.js
    stylesheet:
      - style.css

  - name: solutionSettings-style
    version: 1.0-0
    src: htmlwidgets
    stylesheet:
      - solutionSettings.css
